name: Test trade

on:
  push:
    branches:
      - 'feature/**'

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:

      - name: Checkout code
        uses: actions/checkout@v3     

      - name: Checkout submodule
        run: git clone https://github.com/atreyasinha/autoinvest-liquidate.git

      - name: Setup python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.9'         
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          URL: ${{ secrets.URL }}
          BUYING_POWER: ${{ secrets.BUYING_POWER }}
        run: |
          ls -al
          python order.py