name: Test trade

on:
  push:
    branches:
      - "feature/**"

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.9"

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          URL: ${{ secrets.URL }}
          BUYING_POWER: ${{ secrets.BUYING_POWER }}
        run: |
          python modules/portfolio.py

      - name: commit files
        run: |
          git config --local user.email "atreyavis@gmail.com"
          git config --local user.name "Atreya"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated portfolio" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature/readme
