name: Trade with Alpaca and Finviz

on:
  schedule:
    - cron: '30 16 * * 1-5'             # M-F 9:30 PDT

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:

      - name: Checkout code
        uses: actions/checkout@v3       

      - name: Setup python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.9'         
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: python alpaca_trade.py