name: Update Portfolio

on:
  schedule:
    # every 30th minute past every hour from 14 through 21 on every day-of-week from Monday through Friday
    - cron: "*/30 14-21 * * 1-5"

jobs:
  portfolio-update:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "portfolio"

      - name: Setup python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.9"

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install alpaca-trade-api

      - name: Execute script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
        run: |
          python modules/portfolio.py

      - name: commit files
        run: |
          git config --local user.email "atreyavis@gmail.com"
          git config --local user.name "Atreya"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated portfolio" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: portfolio
