name: Trigger order

on: [workflow_dispatch]

jobs:
  stg:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      - name: Accumulate
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          URL_BM: ${{ secrets.URL_BM }}
          URL_CS: ${{ secrets.URL_CS }}
          URL_CC: ${{ secrets.URL_CC }}
          URL_CD: ${{ secrets.URL_CD }}
          URL_EN: ${{ secrets.URL_EN }}
          URL_FN: ${{ secrets.URL_FN }}
          URL_HL: ${{ secrets.URL_HL }}
          URL_IN: ${{ secrets.URL_IN }}
          URL_RE: ${{ secrets.URL_RE }}
          URL_TC: ${{ secrets.URL_TC }}
          URL_UT: ${{ secrets.URL_UT }}
        run: python modules/accumulate.py

      - name: Liquidate
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
        run: python modules/liquidate.py

  prd:
    needs: stg
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      - name: Accumulate
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          URL_BM: ${{ secrets.URL_BM }}
          URL_CS: ${{ secrets.URL_CS }}
          URL_CC: ${{ secrets.URL_CC }}
          URL_CD: ${{ secrets.URL_CD }}
          URL_EN: ${{ secrets.URL_EN }}
          URL_FN: ${{ secrets.URL_FN }}
          URL_HL: ${{ secrets.URL_HL }}
          URL_IN: ${{ secrets.URL_IN }}
          URL_RE: ${{ secrets.URL_RE }}
          URL_TC: ${{ secrets.URL_TC }}
          URL_UT: ${{ secrets.URL_UT }}
        run: python modules/accumulate.py

      - name: Liquidate
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
        run: python modules/liquidate.py
