name: Trimming

on:
  schedule:
    - cron: "00 16 * * 1-5" # M-F

jobs:
  stg:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.10"

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      - name: Trim
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          MAGIC_NUMBER: ${{ secrets.MAGIC_NUMBER }}
        run: python modules/trim.py

  prd:
    needs: stg
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.10"

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      - name: Trim
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          MAGIC_NUMBER: ${{ secrets.MAGIC_NUMBER }}
        run: python modules/trim.py
